### ISSUE TITLE
Not working anymore ?

### ISSUE THREAD

**Issue by kodama12** [alirezakargar1380/delete_tweetes_scripts#1]
good morning there,

since a couple of days, that kind of script doesn't work anymore, i try to figure out why, it's like script not finding delete button anymore, or maybe the confirmation, not sure about.

How i can help you to fix it please ?

Best regards,

**Comment by alirezakargar1380** [comment]
hey, **thank you for your report** ❤️
I checked that and yeah, it was because the script was unable to find the delete button, I fixed it and now it works.

**Comment by kodama12** [comment]
Thanks sir, i knew old time how to dev, but i'm not used anymore, i try to find by myself how to fix, but i cannot, i read your code update, and i'm still not able to understand;
i saw that "[role="menuitem"" is new ? An update from twitter that document.querySelectorAll('span') doesnt work anymore ?

Thanks a lot sir.
